nelmio_api_doc:
    documentation:
        tags:
           - name: "User"
             description: "APIs related to User operations"
           - name: "Admin"
             description: "APIs related to Admin operations"
        info:
            title: QUIKTRAK APIs
            description: The APIs for the QUIKTRAK inspectors
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api # Accepts routes under /api except /api/doc
